### ISSUE TITLE
Book Documentation: Generate Markdown for JSON Type Definitions

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#100]
### Goal

We have type definitions for components, entity types and relation types. It would be helpful if markdown could be generated automatically from the definitions. This would make the documentation much more consistent and would avoid a lot of repetitive work.

### Tasks

- [ ] Generate `entity_type.md` from `entity_type.json` or `entity_type.json5` or `entity_type.toml`
- [ ] Embed generator in build system
- [ ] Reference to markdown files in the book
