### ISSUE TITLE
Remove IndraDB

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#101]
### History

IndraDB was one of the reasons why Inexor Reactive Graph Flow was implemented with rust. At first RGF built on the functionality of the IndraDB in-memory graph database and made RGF possible at all. There was simply no C++ library which provide the necessary features:

* an embeddable library
* in-memory
* easy to use
* directed graph
* property graph with complex (JSON-like) properties

Later, as more and more functionality has been implemented, RGF itself mutated to an in-memory graph database. Of course RGF doesn't provide as many functionality as IndraDB. Though RGF has everything what's needed for the runtime of a system with reactive nodes and(!) edges: it represents a directed property graph with reactive properties and it's possible to interact with the graph via the rust API and the GraphQL API.

### Goal

Remove IndraDB as part of the RGF runtime.

### Why

1. See history: RGF doesn't depend anymore on the functionality
2. Remove a layer of unnecessary indirection
3. Less code to maintain
4. It makes it possible to refactor the reactive functionality from core-model to core-reactive
5. Reduce dependencies and their transitive dependencies
6. Reduce compilation times
7. Reduce file size of the binary

### Tasks

- [x] Replace EdgeKey with an own implementation
- [x] Representation of relation instances with a instance id
- [x] Remove EntityVertexManager and RelationEdgeManager and their implementations
- [x] Replace import and export functionality and move them to own managers
