### ISSUE TITLE
Use TypedBuilder where possible and move remaining builders into core-model

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#103]
Currently, the builder pattern is implemented of the most models. But it's implemented manually.

Using [TypedBuilder](https://crates.io/crates/typed-builder) there are many benefits:

* The builders are type-safe (wrong usage results in compilation errors)
* Automatically generated builders (less code to maintain and less noise)
* Uniform builders

### Goal

All models provide a type safe builder.

### Tasks

- [x] All or the most models provide the TypedBuilder
- [x] Provide sensible defaults for optional fields
- [x] The usage of the builders are migrated to TypedBuilder where possible
- [x] Old builders without usage are removed
- [x] Builders with usage are moved to core-model or core-reactive if there are specific use cases which are not fullfilled by TypedBuilder
