### ISSUE TITLE
Flow Types

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#49]
### Goal

With a flow type, an abstract flow can be defined and instantiated multiple times. Similar flows can be instantiated using parametrization. Flow types can be nested, which allows reusage of mechanics.

### Use Cases

Everything which can run multiple times at the same time:

* A game mode
* A mechanic of a game mode which is a building block for concrete game modes (for example: flag mechanics is used by multiple game modes)
* A weapon mechanics
* A mechanic of a weapon which is a building block for concrete weapons
* A player
* A team
* A hardware device which exists multiple times
* An identical or similar room which exists multiple times on a map
* An IoT device which exists multiple times
* ...

### Specification

* Flow types can be represented as JSON and can be imported from a JSON file and exported to a JSON file
* Flow types contains:
  * Virtual entity instances
  * Virtual relation instances
  * Specific entity instances (with a specific UUID or path which is known at design time - usually well known singletons)
  * Named entity instances (the entity instance is not known at design time but provided at instantiation)
  * Another flow types (which allows building complex scenarios with abstract sub flows)
* Flows can be instantiated from a flow type multiple times, because the actual UUIDs of the resulting entity instances are generated at instantiation time
* Immediate UUIDs
  * Virtual entity instances have an immediate UUID
  * Virtual relation instances connects virtual entity instances (and uses the immediate UUIDs of the outbound + inbound virtual entity instances)
* Dynamic Instantiation
  * Flow type parameters
    * Flow types can define named parameters
    * The value of the properties of the virtual entity instances and virtual relation instances can use named parameters
    * At instantiation of a flow from a flow type, the value of the named parameters are replaced by the provided values
  * Flow type instances
    * Flow types can define named entity instances
    * The UUIDs of virtual entity instances can use an entity instance name
    * At instantiation of a flow from a flow type, the UUIDs of the named entity instances are replaced by the provided entity instances

### Tasks

- [x] Import a flow type from JSON
- [x] Export a flow type to JSON
- [x] Create a new flow type
- [x] Delete a flow type
- [ ] Update a flow type
  - [ ] Add a virtual entity instance to a flow type
  - [ ] Remove a virtual entity instance to a flow type
  - [ ] Add a virtual relation instance to a flow type
  - [ ] Remove a virtual relation instance to a flow type
- [x] Create a flow (instance) from a flow type
  - [x] Replace the immediate UUIDs in virtual entity instances and virtual relation instances
  - [ ] Replace the named parameters
  - [ ] Replace the named entity instance by the provided concrete entity instance
  - [ ] Create the flows for the nested flow types
- [x] Extend Plugin API
  - [x] FlowTypeProvider
- [x] ChangeLog
- [ ] Documentation
- [x] Tests

**Comment by aschaeffer** [comment]
Mostly done in #58. The remaining task will follow in separate pull requests.
