### ISSUE TITLE
GraphQL: Dynamic Graph: Live-Introspection

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#55]
## Goal

The goal is that GraphQL clients can resolve the [GraphQL schema](https://graphql.org/learn/schema/) via [GraphQL Introspection](https://graphql.org/learn/introspection/). This is the second step for the [Dynamic Graph](https://github.com/inexorgame/inexor-rgf-application/issues/18) feature.

## TODOs

- [x] Type System Changed Event
- [x] `__Schema`
- [x] `__Type`
  - [x] `kind` => `OBJECT`
  - [x] `name`
  - [x] `description`
  - [x] `fields`
    - [x] `name`
    - [x] `description`
    - [ ] `args`
      - [ ] ... `InputValue`
    - [x] `isDeprecated` => `false`
    - [x] `deprecationReason` => `null`
    - [ ] `inputFields`
      - [ ] ... `InputValue`
    - [x] `interfaces` => empty vec
    - [x] enumValues
      - [x] `name`
      - [x] `description`
      - [x] `isDeprecated` => `false`
      - [x] `deprecationReason` => `null`
    - [x] `possibleTypes`
      - [x] unions
      - [x] union members
- [x] `queryType`
  - [x] The root query type contains all Entity Types as fields (not the Components)
- [x] `mutationType` => `null` (yet)
- [x] `subscriptionType` => `null` (yet)
- [x] `directives` => List of directives
    
    
## Reference

Altair GraphQL Client sends this introspection query:

```graphql
query IntrospectionQuery {
  __schema {

    queryType { name }
    mutationType { name }
    subscriptionType { name }
    types {
      ...FullType
    }
    directives {
      name
      description

      locations
      args {
        ...InputValue
      }
    }
  }
}

fragment FullType on __Type {
  kind
  name
  description

  fields(includeDeprecated: true) {
    name
    description
    args {
      ...InputValue
    }
    type {
      ...TypeRef
    }
    isDeprecated
    deprecationReason
  }
  inputFields {
    ...InputValue
  }
  interfaces {
    ...TypeRef
  }
  enumValues(includeDeprecated: true) {
    name
    description
    isDeprecated
    deprecationReason
  }
  possibleTypes {
    ...TypeRef
  }
}

fragment InputValue on __InputValue {
  name
  description
  type { ...TypeRef }
  defaultValue


}

fragment TypeRef on __Type {
  kind
  name
  ofType {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by aschaeffer** [comment]
Components as GraphQL Type (right, prefixed with a `c`)
Entity Types as GrapahQL Type (left)
![grafik](https://user-images.githubusercontent.com/2207279/188268438-be823292-cf4f-45c7-a5a5-91dbe6fdcc73.png)

**Comment by aschaeffer** [comment]
https://github.com/inexorgame/inexor-rgf-application/commit/033c946e0f2e98dbb93a27b76482ae13bb60eed4

**Comment by aschaeffer** [comment]
Done by using [async-graphql 5.0.0](https://github.com/async-graphql/async-graphql/issues/30)
