### ISSUE TITLE
GraphQL: Dynamic Graph: Implement Resolvers for Querying the Instance System

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#56]
## Goal

Implement resolvers for querying the RGF instance system (entity instances, relation instances). This is the third step for the [Dynamic Graph](https://github.com/inexorgame/inexor-rgf-application/issues/18) feature.

## Tasks

- [x] Implement `NameSpaceManager` to get all namespaces used in components, entity types, relation types and flow types
- [x] Implement Root Query
- [x] Generate objects for all namespaces
- [x] Generate interfaces for all components (prefixed by namespace, suffixed by `Component`)
- [x] Generate interface `Entity` for entity objects
- [x] Generate interface `Relation` for relation objects
- [x] Generate objects for all entity types (prefixed by namespace, suffixed by `Entity`)
- [x] Generate fields for an entity (entity type properties + component properties)
  - [x] boolean
  - [x] f64 number
  - [x] i64 number
  - [x] u64 number
  - [x] string
  - [x] array
  - [x] object
  - [x] Check for divergent data types (component vs. entity type)
- [x] Generate fields for relations of an entity
- [x] Generate objects for all relation types (prefixed by namespace, suffixed by `Relation`)
- [x] Generate fields for a relation
- [x] Generate fields for the outbound entity of a relation
- [x] Generate fields for the inbound entity of a relation
- [x] Generate unions `AllEntities` and `AllRelations`
- [x] Generate unions for all entities of a namespace
- [x] Generate unions for all relations of a namespace
- [x] Improved relation naming
  - [x] Make it possible to rename an outbound entity field of a relation
  - [x] Make it possible to rename an inbound entity field of a relation
  - [x] Make it possible to rename an outbound relation field of an entity
  - [x] Make it possible to rename an inbound relation field of an entity
- [x] Shortcut relation links
  - [x] Make it possible to link directly from an entity to the entity of an outbound relation (skip the relation itself)
  - [x] Make it possible to link directly from an entity to the entity of an inbound relation (skip the relation itself)
- [ ] Exclusions
  - [ ] Make it possible to exclude a component
  - [ ] Make it possible to exclude an entity type
  - [ ] Make it possible to exclude a relation type
  - [ ] Make it possible to exclude field of a component
  - [ ] Make it possible to exclude field of an entity
  - [ ] Make it possible to exclude field of a relation
