### ISSUE TITLE
Improve Reactive Behaviours API

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#61]
### Disadvantages of Reactive API 0.7.0

- Registration of behaviours has a lot of boilerplate code in each plugin
- Management of behaviours is decentralized and repetitive
- In order to be able to restart plugins, behaviours have to shut down gracefully

#### 1. Finite State Machine

- Reduce boilerplate code in plugins
- Streamline plugin implementations
- Abstract common code into base crates
- Implement a finite state machine for behaviours and state transitions 
- Implement a framework which provides extension points for
  - initialization
  - validation
  - connecting (internal wiring)
  - disconnecting
  - reconnecting
  - query state

#### 2. Validation

- Standardize validation of behaviours
- Provide macros for defining a validator easily

#### 3. Connect & Disconnect

- Implement a framework which manages the observer handles
- Automatically drop stream observers when the behaviour drops
- Integrate managed observers with the finite state machine

#### 4. Centralized Behaviour Store "Behaviours are First Class Citizens"

- Extent model to have behaviours as first class citizens
- Change service method signatures to use behaviour types
- Centralize behaviour storages with a two-level-hashmap containing the entity id/relation edge key and the behaviour type as hash keys.
- Provide a registration interface for plugins which registers and unregisters behaviours to the centralized behaviour storage

### Tasks

- [x] Behaviour Validation
- [x] Behaviour Error Types
- [x] Require Drop
- [x] Behaviour Container
    - [x] ty()
- [x] Reactive Instance Container
    - [x] get_reactive_instance()
- [x] Behaviour Finite State Machine
    - [x] get_state()
    - [x] transition(state: BehaviourState)
        - [x] Created --validate()--> Validated
            - [x] `validate()`
        - [x] Validated --init()--> Ready
            - [x] `init()`
        - [x] Ready --connect()--> Connected
            - [x] `connect()`
            - [x] Automatically add behaviour `reactive_instance.add_behaviour()`
        - [x] Connected --disconnect()--> Ready
            - [x] disconnect()
            - [x] Automatically remove behaviour `reactive_instance.remove_behaviour()`
        - [x] Ready --shutdown()--> Drop
            - [x] `shutdown()`
    - [x] enum BehaviourState
        - [x] Created
        - [x] Validated
        - [x] Ready
        - [x] Connected
- [x] BehaviourStorage
    - [x] ComponentBehaviourStorage
    - [x] EntityBehaviourStorage
    - [x] RelationBehaviourStorage
    - [x] EntityComponentStorage
    - [x] RelationComponentStorage
- [x] Centralized Behaviour Management
    - [x] Registry for EntityBehaviours
    - [x] Registry for EntityComponentBehaviours
    - [x] Registry for RelationBehaviours
    - [x] Registry for RelationComponentBehaviours
    - [x] Plugin Interface
    - [x] Gracefully shutdown plugin
        - [x] Shutdown all behaviours on plugin shutdown
- [x] Macros
    - [x] behaviour!
    - [x] behaviour_factory!
    - [x] behaviour_fsm!
    - [x] behaviour_transitions!
    - [x] behaviour_types!
- [x] GraphQL Behaviours Query
    - [x] Behaviour GraphQL Types
        - [x] EntityBehaviour
            - [x] EntityInstances
        - [x] EntityComponentBehaviour
        - [x] RelationBehaviour
            - [x] RelationInstances
        - [x] RelationComponentBehaviour
    - [x] Components
        - [x] List Component Behaviours
    - [x] Entity Types
        - [x] List Entity Behaviours
        - [x] Count Entity Behaviours
        - [x] Count Entity Behaviours Instances
        - [x] Count Entity Component Behaviours
        - [x] Count Entity Component Behaviours Instances
    - [x] Relation Types
        - [x] List Relation Behaviours
        - [x] Count Relation Behaviours
        - [x] Count Relation Behaviours Instances
        - [x] Count Relation Component Behaviours
        - [x] Count Relation Component Behaviours Instances
    - [x] Entity Instance
        - [x] EntityBehaviours
        - [ ] Behaviour State (created, ready, connected)
        - [x] EntityComponentBehaviours
    - [x] Relation Instance
        - [x] RelationBehaviours
        - [ ] Behaviour State (created, ready, connected)
        - [x] RelationComponentBehaviours
- [x] GraphQL Behaviour Mutations
    - [x] Entity Instance
        - [x] Mutation: Reconnect Behaviour(behaviour_ty)
        - [x] Mutation: Disconnect Behaviour
        - [x] Mutation: Connect Behaviour
    - [x] Relation Instance
        - [x] Mutation: Reconnect Behaviour(behaviour_ty)
        - [x] Mutation: Disconnect Behaviour
        - [x] Mutation: Connect Behaviour
