### ISSUE TITLE
GraphQL: Dynamic Graph: Implement Resolvers to Mutate the Instance System

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#64]
## Goal

Implement resolvers to mutate the RGF instance system (entity instances, relation instances). This is the fourth step of the [Dynamic Graph](https://github.com/inexorgame/inexor-rgf-application/issues/18) feature.

## Tasks

- [ ] Implement Root Mutation
- [ ] Generate objects for all namespaces
- [ ] Generate "Create" operation for all entity types of a namespace
  - [ ] Return the created entity instance
- [ ] Generate "Update" operation for all entity types of a namespace
  - [ ] Query entity instances by filters
    - [ ] By ID
    - [ ] By label
    - [ ] By property value(s)
    - [ ] By having a component
    - [ ] By having a behaviour
  - [ ] Update reactive stream of the entity instance property
  - [ ] Return the updated entity instance(s)
- [ ] Generate "Delete" operation for all entity types of a namespace
- [ ] Generate "Create" operation for all relation types of a namespace
  - [ ] Return the created relation instance
- [ ] Generate "Update" operation for all relation types of a namespace
  - [ ] Query entity instances by filters
    - [ ] By ID
    - [ ] By label
    - [ ] By property value(s)
    - [ ] By having a component
    - [ ] By having a behaviour
  - [ ] Update reactive stream of the relation instance property
  - [ ] Return the updated relation instance(s)
- [ ] Generate "Delete" operation for all relation types of a namespace
