### ISSUE TITLE
Improve Plugin Hot Reloading

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#67]
## Problems

1. Currently, no build is triggered for a plugin if ...
    - The type system definition has changed
    - The source code hasn't changed
2. While redeploying plugins, already registered type system definitions are ignored
3. Plugin hangs in refresh transition

## Goal

1. Reduce application restarts
2. Add multi instance capability

## Tasks

- [x] Rebuild if `types/**/.json` have changed
  * `build.rs` [cargo:rerun-if-changed](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorerun-if-changedpath)
- [x] Merge type system definitions (#73)
- [x] Fix refresh transition
- [x] Add configuration option for disable/enable hot reloading
- [x] Add configuration options for plugin folders
- [x] Remove duplicate plugin files in installation folder on startup
- [x] Yield during plugin resolving to avoid blocking the async runtime
