### ISSUE TITLE
Improve flexibility of behaviours

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#68]
## Problem

1. There are plugins which reactive instances interacts with the business layer (`file::fs_notify`, `scheduler::scheduler`)
2. There are plugins which reactive instances runs in threads / asynchronously
3. There are plugins which have to implement a different behaviour on disconnect

## Tasks

- [ ] Make it possible to implement a different behaviour on disconnect
- [ ] Make it possible to store thread handles in a behaviour
- [ ] Make it possible to stop and clean up threads on disconnect
- [ ] Make it possible to construct a behaviour which having a tokio runtime
