### ISSUE TITLE
GraphQL Test Automation

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#70]
## Goal

Automatically test GraphQL endpoints

## Idea

Create a bunch of GraphQL queries and mutations and also store the expected result in a snapshot.

## Test Lifecycle

- Optional: Setup Mutation
- Query / Mutation
- Optional: Verification Query
- Optional: Cleanup Mutation

## Tasks

- [x] Implement a scanner for GraphQL tests `*.graphql` and their snapshots `*.json`
- [x] Start a `inexor-rgf-runtime`
- [x] Iterate through all files and execute tests
  - [x] Execute a setup mutation `name__setup.graphql`
  - [x] Execute the GraphQL query/mutation `name.graphql` via `GraphQLQueryService` / `GraphQLDynamicQueryService`
  - [x] Execute a verification query `name__verify.graphql`
  - [x] Execute a cleanup mutation `name__cleanup.graphql`
  - [x] Compare actual JSON result with the expected snapshot
- [x] Implement a scanner for Dynamic Graph tests `*.graphql` and their snapshots `*.json`
- [ ] Make it run on GitHub Actions
- [ ] #77
- [ ] #78

## Bonus Tasks

- [ ] Does this increase the test coverage?
- [ ] Provide the GraphQL test cases in the mdbook documentation

## Depends on

- [x] #65
- [x] #75
- [x] #76

## Crates

* [Faker](https://crates.io/crates/fake)
