### ISSUE TITLE
Merge existing type definitions

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#73]
### Goal

Merge modified type definitions into existing type definitions.

### Use Cases

* Hot reloading plugins with modified type definitions
* Flow Editor modifies type definitions

### Merge Strategy

1. Add new
2. Overwrite existing
3. Don't remove anything

### Tasks

- [x] Merge component definition
  - [x] Overwrite description
  - [x] Properties
    - [x] Add non-existing properties
    - [x] Overwrite description for existing properties
    - [x] Overwrite data type for existing properties
    - [x] Overwrite socket type for existing properties
    - [x] Overwrite mutability for existing properties
  - [x] Property Extensions
    - [x] Add non-existing property extensions
    - [x] Overwrite description for existing property extensions
    - [x] Overwrite extension (content) for existing property extensions
  - [x] Extensions
    - [x] Add non-existing extensions
    - [x] Overwrite description for existing extensions
    - [x] Overwrite extension (content) for existing extensions
- [x] Merge entity type definition
  - [x] Overwrite description
  - [x] Components
    - [x] Add non-existing components and their properties
  - [x] Properties
    - [x] Add non-existing properties
    - [x] Overwrite description for existing properties
    - [x] Overwrite data type for existing properties
    - [x] Overwrite socket type for existing properties
    - [x] Overwrite mutability for existing properties
  - [x] Property Extensions
    - [x] Add non-existing property extensions
    - [x] Overwrite description for existing property extensions
    - [x] Overwrite extension (content) for existing property extensions
  - [x] Extensions
    - [x] Add non-existing extensions
    - [x] Overwrite description for existing extensions
    - [x] Overwrite extension (content) for existing extensions
- [x] Merge relation type definition
  - [x] Overwrite description
  - [x] Overwrite outbound type
  - [x] Overwrite inbound type
  - [x] Components
    - [x] Add non-existing components and their properties
  - [x] Properties
    - [x] Add non-existing properties
    - [x] Overwrite description for existing properties
    - [x] Overwrite data type for existing properties
    - [x] Overwrite socket type for existing properties
    - [x] Overwrite mutability for existing properties
  - [x] Property Extensions
    - [x] Add non-existing property extensions
    - [x] Overwrite description for existing property extensions
    - [x] Overwrite extension (content) for existing property extensions
  - [x] Extensions
    - [x] Add non-existing extensions
    - [x] Overwrite description for existing extensions
    - [x] Overwrite extension (content) for existing extensions

### Follow Up

- [ ] #79
