### ISSUE TITLE
Refactor into runtime and standalone executable

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#75]
### Goals

1. Make `inexor-rgf` to be embeddable
2. Make it possible to create integration tests

### Use cases

1. Embed runtime into reactive graph flow editor
2. Use runtime for testing GraphQL queries
3. Use runtime for testing plugins
4. Simulate synchronization of multiple runtimes

### Tasks

- [x] Create a lib crate
  - [x] Create an entry point for creating a runtime
  - [x] Refactor `async-std` to `tokio`
  - [x] Refactor graceful shutdown
- [x] Create an exe crate
  - [x] Initialize the runtime
  - [x] Use `tokio::main`

**Comment by aschaeffer** [comment]
1412a1da
