### ISSUE TITLE
Make it possible to configure the runtime at creation

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#76]
### Goal

The runtime initializes using configuration files that are relative to the working directory. It shall be possible to start a runtime programmatically with custom configurations.

### Use Cases

1. Integration tests for plugins which initializes the runtime and the necessary plugins only
2. Automate GraphQL interface tests
3. Start new embedded runtimes from the flow editor (at runtime)
4. Run isolated runtimes at the same time to simulate communication (c2s, s2s, p2p)

### Tasks

- [x] Runtime Configuration (wrapper)
  - [x] GraphQL Server Configuration
  - [x] Instance Configuration
- [x] Standalone executable Command Line Arguments
  - [x] Configuration location(s)
  - [x] GraphQL server configuration
  - [x] Instance configuration
- [x] Runtime Builder
  - [x] Create a runtime using the builder pattern
  - [x] Programmatically created configurations (for integration tests / automated interface tests)
