### ISSUE TITLE
Type System Persistence

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#82]
### Current State

Currently, the type system is initialized by type providers in the plugins. Type system modifications are lost after restarting the runtime.

### Goals

It is possible to create, modify and persist types. Created and modified types are loaded after restarting the runtime.

The Reactive Flow Editor will be much more useful if it is possible to persist types.

### Tasks

- [ ] Separate import and export from type managers
  - [ ] `ComponentImportExportManager`
  - [ ] `EntityTypeImportExportManager`
  - [ ] `RelationTypeImportExportManager`
  - [ ] `FlowTypeImportExportManager`
  - [ ] Make type managers available via Plugin Context
  - [ ] Make type managers available via Runtime API
  - [ ] GraphQL API
- [ ] Support more data formats
  - [ ] JSON
  - [ ] JSON5
  - [ ] TOML
- [ ] Repositories
  - [ ] Load types from local repositories
    - [ ] Create new if non-existing
    - [ ] Merge if existing
      - [ ] Set state in type, that it has been merged
  - [ ] Support multiple repositories
  - [ ] Persist types on change
    - [ ] Set state in type, if it has been modified
    - [ ] Save type
      - [ ] Remove state in type, that it has been modified
  - [ ] Restore original type
    - [ ] Delete type in repository
    - [ ] Remove state in type, that it has been merged
- [ ] Options
  - [ ] Option to lock the type system
    - [ ] Types cannot be modified via Runtime API, Plugin API, GraphQL and CLI
    - [ ] Types cannot be loaded from a repository
  - [ ] Option to disable loading types from repositories
    - [ ] Types can be created and modified by Runtime API, Plugin API, GraphQL and CLI
    - [ ] Types cannot be loaded from a repository
  - [ ] Option to disable persisting types to repositories
    - [ ] Types can be created and modified by Runtime API, Plugin API, GraphQL and CLI
    - [ ] Types cannot be persisted into a repository
    - [ ] After restarting the runtime, all changes are lost

### Challenges

* Merging types is a non-trivial task
* How to persist "deletions"?

### Future

1. Later, it will be possible to fetch remote repositories via git (maybe using the plugin inexor-rgf-plugin-git).
2. Hot reload types on file system modification
