### ISSUE TITLE
CLI REPL

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#83]
### Goal

The inexor executable is able to run the CLI in a REPL. The REPL-CLI is able to support the
user with suggestions, autocomplete and help.

### Tasks

- [x] Repeat Readline
- [x] Show Prompt
- [x] Hint last command state was successful or errored
- [x] Hint input is a valid command
- [x] Hint input has errors
- [x] Show subcommand suggestions
- [x] Show argument suggestions
- [x] Autocomplete
  - [x] If only one suggestion: Select the only suggestion and add a spacer
  - [x] If there are multiple suggestions: Complete the longest common prefix (no spacer)
- [x] History
    - [x] Load History
    - [x] History Search
    - [x] Save History
- [x] Handle quotes mismatch
- [x] Handle CTRL-D: Exit
- [x] Handle CTRL-C
    - [x] Once
        - [x] Clear command
        - [x] Hint that you can press CTRL-C another time to exit
    - [x] Twice: Exit

### Follow Up

- #97 
- #98
