### ISSUE TITLE
Management of Remote Instances

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#86]
### Goal

The runtime (`inexor_rgf_rt`) provides information about itself (for example, the name and a description). The runtime manages a list of known remote instances. Remote instance can be added and removed. The runtime checks if the remotes are up and running and fetches their instance information. The functionality is available via API, GraphQL API, Client API and CLI.

### Why

This is a milestone on the road to synchronization and interoperability between multiple instances. It may allow distributed systems and in the future.

### Tasks

- [x] Instance Info
    - [x] Manager
    - [x] GetInstanceInfo
        - [x] Service API
        - [x] Service Impl
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
- [x] Remote Instances
    - [x] Manager
    - [x] Has(Address)
        - [x] Service API
        - [x] Service Impl
    - [x] Get(Address)
        - [x] Service API
        - [x] Service Impl
    - [x] GetAll
        - [x] Service API
        - [x] Service Impl
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] Add(Address)
        - [x] Service API
        - [x] Service Impl
        - [x] Persistence (Update remotes.toml)
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] Remove(Address)
        - [x] Service API
        - [x] Service Impl
        - [x] Persistence (Update remotes.toml)
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] RemoveAll
        - [x] Service API
        - [x] Service Impl
        - [x] Persistence (Update remotes.toml)
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] Update(Address)
        - [x] Service API
        - [x] Service Impl
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] UpdateAll
        - [x] Service API
        - [x] Service Impl
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] FetchRemotesFromRemote(Address)
        - [x] Service API
        - [x] Service Impl
        - [x] Persistence (Update remotes.toml)
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] FetchRemotesFromAllRemotes
        - [x] Service API
        - [x] Service Impl
        - [x] Persistence (Update remotes.toml)
        - [x] GraphQL API
        - [x] GraphQL Test
        - [x] GraphQL Documentation + Example
        - [x] Inexor Client
        - [x] Inexor Client Test
        - [x] CLI Table Model
        - [x] CLI Args
        - [x] CLI Commands
    - [x] Startup
        - [x] Persistence (Load remotes.toml)
