### ISSUE TITLE
Implement Commands for Managing Remote Instances

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#88]
### Goal

Followup of #86 - Provide commands for the command system.

### Tasks

- [ ] Remote Instances
    - [ ] GetAll
        - [ ] Inexor Command `remotes::list`
        - [ ] Inexor Command Test
    - [ ] Add(Address)
        - [ ] Inexor Command `remotes::add hostname port secure`
        - [ ] Inexor Command Test
    - [ ] Remove(Address)
        - [ ] Inexor Command `remotes::remove hostname port secure`
        - [ ] Inexor Command Test
    - [ ] RemoveAll
        - [ ] Inexor Command `remotes::remove_all`
        - [ ] Inexor Command Test
    - [ ] Update(Address)
        - [ ] Inexor Command `remotes::update hostname port secure`
        - [ ] Inexor Command Test
    - [ ] UpdateAll
        - [ ] Inexor Command `remotes::update_all`
        - [ ] Inexor Command Test
    - [ ] FetchRemotesFromRemote(Address)
        - [ ] Inexor Command `remotes::fetch_remotes_from_remote hostname port secure`
        - [ ] Inexor Command Test
    - [ ] FetchRemotesFromAllRemotes
        - [ ] Inexor Command `remotes::fetch_remotes_from_all_remotes`
        - [ ] Inexor Command Test
