### ISSUE TITLE
GraphQL: Correct Return Values of Delete Operations

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-application#91]
### Goal

1. The GraphQL endpoints returns true if a type has been deleted
2. The GraphQL endpoints returns false if a type wasn't deleted (for example: it didn't exist)

### Tasks

- [x] Delete Component
- [x] Delete Entity Type
- [x] Delete Relation Type
- [x] Delete Flow Type
- [x] Delete Entity Instance
- [x] Delete Relation Instance
- [x] Delete Flow Instance
